### ISSUE TITLE
sticky - "updateStateParams" transition when pass object param between states

### ISSUE THREAD

**Issue by dmaciaszek** [christopherthielen/ui-router-extras#251] opened 2015-10-09 10:45 UTC
Hi,
I have some problem with sticky mode in my app. I have many states based in tab elements. I want to save every view when I switch between tabs, but if I come back to some tab, state is not 'reactivate' but  is 'updateStateParams'. Between states a pass by params some Object like { name: 'someName', age : 20, active : true}. When I switch between tabs I do not change anything in my params object. I discovered that in your sticky script stateParams are compared with inactiveState params. In my case compared objects are the same but in my opinion comparision method is wrong.  It is some lines in sticky script (line 139):

if (!angular.equals(a[k], b[k])) return false; // Not '===', values aren't necessarily normalized

As I wrote I pass in params OBJECT not primitive. This code compare values only for primitives. For object I think should use e.g. angular.equals method. My object are equal but this script think that is not so return false what couses 'updateStateParams' transition (I think it is wrong because a do not change my params object).

So my question is...It is a bug or it is intentional to compare reference to object not value?

**Comment by christopherthielen** [comment] 2015-10-09 13:49
I think this is a dupe of #239 and it is fixed in 0.0.15-pre2. Can you try the version found in the plunk for issue 239 and let me know if it works for you?

**Closed** 2015-10-09 21:11 UTC
Labels: duplicate, stickystate

**Comment by christopherthielen** [comment] 2015-10-09 21:15
here's a link to 0.0.15-pre3

https://rawgit.com/christopherthielen/dc4f7a04e89580f4ecab/raw/c6208c1d8713bfde1885580d2b2ec87cbc317f9c/ct-ui-router-extras.js

**Comment by dmaciaszek** [comment] 2015-10-09 21:24
Thank you for quick reply and link.

**Comment by christopherthielen** [comment] 2015-10-09 21:25
let me know if it works for you

**Comment by dmaciaszek** [comment] 2015-10-09 21:28
Ok I will let you know next week. Thanks.

**Comment by dmaciaszek** [comment] 2015-10-13 14:16
It is working fine. Thanks again.
