### ISSUE TITLE
from sticky state to sticky state

### ISSUE THREAD

**Issue by david2tm** [christopherthielen/ui-router-extras#248] opened 2015-09-27 13:22 UTC
I see an issue, don't know if it's on purpose, But I will try to explain.
Plunker: http://plnkr.co/edit/iovSdLG52ezYgsfn46BU

There're two sticky states (task-bar / content)
1. Try switching for task-bar only for "a" to "b" (using buttons) you will see, that "a" exited, and "b" entered.
2. Now from "b" to "c" - same story. And this is OK.
3. Now, whilst task-bar.c is active, activate content.a, task-bar.c became inactive, whilst content.a activated. And this is OK.
4. Try activating content.b. You will see that task-bar.c remains inactive, content.a exiting, content.b activates. So far, good.
5. Now activate task-bar.d.
  1. content.b -> inactive = OK
  2. task-bar.d -> active = OK
  3. task-bar.c -> inactive = **Not OK**

So, is this is on purpose?
If not, I believe I can create PR with fix. [ e8619010b2b932496c02d92b06f4f9f41d340c61 , a635b782543a9aaabb10ffcf3c5c258d95d471df ] but not sure it will work with sticky inside sticky and other complicated scenarios.

**Comment by christopherthielen** [comment] 2015-10-03 17:15
Hi, yes that is a known bug, a dupe of #217.  I think it is related to a couple other bugs, and there is an active PR #224 that may fix it.  

I need to find a couple hours to really dig into this one and make sure the PR is correct.

**Comment by christopherthielen** [comment] 2015-10-03 17:16
@david2tm in the meantime, see if version 0.0.13 works for you.

**Comment by christopherthielen** [comment] 2015-10-05 16:03
@david2tm I've got a fix for this committed to master.  Here's your plunker running correctly using ui-router-extras 0.0.15-pre1

http://plnkr.co/edit/gjy2WNixpKmv1Y2pQkZU?p=preview

**Closed by christopherthielen** 2015-10-05 16:03 UTC
Labels: bug, stickystate

**Comment by david2tm** [comment] 2015-10-06 03:38
Great, thanks.
